name: cdips
channels:
  - anaconda
  - astropy
  - defaults
dependencies:
  - asn1crypto=0.24.0=py37_0
  - astropy-healpix=0.4=py37h3010b51_1000
  - astroquery=0.3.9=py_1000
  - atomicwrites=1.3.0=py37_1
  - attrs=19.1.0=py37_1
  - backcall=0.1.0=py37_0
  - beautifulsoup4=4.7.1=py37_1
  - blas=1.0=mkl
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py37_0
  - cffi=1.12.3=py37h2e261b9_0
  - chardet=3.0.4=py37_1
  - cryptography=2.6.1=py37h1ba5d50_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py37_1
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - html5lib=1.0.1=py37_0
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py37_0
  - intel-openmp=2019.3=199
  - ipython=7.4.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.13.3=py37_0
  - jeepney=0.4=py37_0
  - jpeg=9b=h024ee3a_2
  - keyring=18.0.0=py37_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - matplotlib=3.0.3=py37h5429711_0
  - mkl=2019.3=199
  - mkl_fft=1.0.10=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - more-itertools=6.0.0=py37_0
  - ncurses=6.1=he6710b0_1
  - numpy-base=1.16.3=py37hde5b4d6_0
  - openssl=1.1.1=h7b6447c_0
  - pandas=0.24.2=py37he6710b0_0
  - parso=0.4.0=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.0.3=py37_0
  - pluggy=0.9.0=py37_0
  - prompt_toolkit=2.0.9=py37_0
  - psutil=5.6.1=py37h7b6447c_0
  - ptyprocess=0.6.0=py37_0
  - py=1.8.0=py37_0
  - pycparser=2.19=py37_0
  - pygments=2.3.1=py37_0
  - pyopenssl=19.0.0=py37_0
  - pyqt=5.9.2=py37h05f1152_2
  - pysocks=1.6.8=py37_0
  - pytest=4.4.1=py37_0
  - pytest-arraydiff=0.3=py_0
  - pytest-astropy=0.5.0=py_0
  - pytest-doctestplus=0.3.0=py_0
  - pytest-openfiles=0.3.1=py_0
  - pytest-remotedata=0.3.1=py_0
  - python=3.7.3=h0371630_0
  - pytz=2019.1=py_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - reproject=0.4=py37h3010b51_1000
  - requests=2.21.0=py37_0
  - secretstorage=3.1.1=py37_0
  - setuptools=41.0.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - soupsieve=1.8=py37_0
  - sqlite=3.28.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - traitlets=4.3.2=py37_0
  - urllib3=1.24.1=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.33.1=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - argparse==1.4.0
    - astropy==3.1.2
    - batman-package==2.4.6
    - configparser==3.7.4
    - cycler==0.10.0
    - future==0.17.1
    - jplephem==2.9
    - kiwisolver==1.0.1
    - llvmlite==0.28.0
    - numba==0.43.1
    - numpy==1.16.3
    - parse==1.12.0
    - patsy==0.5.1
    - pillow==6.0.0
    - progressbar2==3.42.0
    - pyeebls==0.1.6
    - pygam==0.8.0
    - pyparsing==2.4.0
    - python-dateutil==2.8.0
    - python-utils==2.3.0
    - scikit-learn==0.20.3
    - scipy==1.2.1
    - six==1.12.0
    - statsmodels==0.9.0
    - tornado==6.0.2
    - tqdm==4.31.1
    - transitleastsquares==1.0.23
    - wotan==1.0.4
prefix: /home/lbouma/miniconda3/envs/cdips

